import type { PreparationTemplateItem } from './types/preparation';

export const PREPARATION_TEMPLATE_VERSION = 1;

export const PREPARATION_TEMPLATE: readonly PreparationTemplateItem[] = [
  {
    id: 'default-official-sevk-application',
    templateKey: 'official-sevk-application',
    introducedInVersion: 1,
    title: 'Sevk başvurusu durumunu kontrol et',
    category: 'official',
    sortOrder: 100,
    priority: 'important',
    helper: 'Güncel durumunu e-Devlet’teki Askerliğim hizmetinden veya askerlik şubenden doğrulayabilirsin.',
  },
  {
    id: 'default-official-sevk-document',
    templateKey: 'official-sevk-document',
    introducedInVersion: 1,
    title: 'Sevk belgesini al',
    category: 'official',
    sortOrder: 200,
    priority: 'important',
    helper: 'Belgeyi e-Devlet’teki Askerliğim hizmetinden veya durumuna göre askerlik şubenden alabilirsin.',
  },
  {
    id: 'default-official-reporting-date',
    templateKey: 'official-reporting-date',
    introducedInVersion: 1,
    title: 'Katılacağın tarihi kontrol et',
    category: 'official',
    sortOrder: 300,
    priority: 'important',
    helper: null,
  },
  {
    id: 'default-official-travel-time',
    templateKey: 'official-travel-time',
    introducedInVersion: 1,
    title: 'Tanınan yol süresini kontrol et',
    category: 'official',
    sortOrder: 400,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-official-unit',
    templateKey: 'official-unit',
    introducedInVersion: 1,
    title: 'Birlik / eğitim merkezi bilgilerini kontrol et',
    category: 'official',
    sortOrder: 500,
    priority: 'important',
    helper: null,
  },
  {
    id: 'default-official-allowance',
    templateKey: 'official-allowance',
    introducedInVersion: 1,
    title: 'Yol ve iaşe bedeli bilgilerini kontrol et',
    category: 'official',
    sortOrder: 600,
    priority: 'normal',
    helper: 'Ödeme ve hak bilgileri kişisel sevk durumuna göre değişebilir.',
  },
  {
    id: 'default-documents-identity',
    templateKey: 'documents-identity',
    introducedInVersion: 1,
    title: 'T.C. kimlik kartını hazırla',
    category: 'documents',
    sortOrder: 100,
    priority: 'important',
    helper: null,
  },
  {
    id: 'default-documents-sevk',
    templateKey: 'documents-sevk',
    introducedInVersion: 1,
    title: 'Sevk belgesini hazırla',
    category: 'documents',
    sortOrder: 200,
    priority: 'important',
    helper: null,
  },
  {
    id: 'default-documents-personal',
    templateKey: 'documents-personal',
    introducedInVersion: 1,
    title: 'Gerekli kişisel belgelerini kontrol et',
    category: 'documents',
    sortOrder: 300,
    priority: 'normal',
    helper: 'Kendi durumun için istenen belgeleri resmî kanallardan doğrula.',
  },
  {
    id: 'default-travel-method',
    templateKey: 'travel-method',
    introducedInVersion: 1,
    title: 'Ulaşım şeklini belirle',
    category: 'travel',
    sortOrder: 100,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-travel-ticket',
    templateKey: 'travel-ticket',
    introducedInVersion: 1,
    title: 'Biletini al',
    category: 'travel',
    sortOrder: 200,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-travel-route',
    templateKey: 'travel-route',
    introducedInVersion: 1,
    title: 'Birliğe nasıl ulaşacağını kontrol et',
    category: 'travel',
    sortOrder: 300,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-travel-arrival',
    templateKey: 'travel-arrival',
    introducedInVersion: 1,
    title: 'Varış saatini planla',
    category: 'travel',
    sortOrder: 400,
    priority: 'important',
    helper: null,
  },
  {
    id: 'default-money-card',
    templateKey: 'money-card',
    introducedInVersion: 1,
    title: 'Kullanacağın banka kartını hazırla',
    category: 'moneyCommunication',
    sortOrder: 100,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-money-budget',
    templateKey: 'money-budget',
    introducedInVersion: 1,
    title: 'Askerlik süresindeki para ihtiyacını planla',
    category: 'moneyCommunication',
    sortOrder: 200,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-money-phone',
    templateKey: 'money-phone',
    introducedInVersion: 1,
    title: 'Telefon hattı kullanımını kontrol et',
    category: 'moneyCommunication',
    sortOrder: 300,
    priority: 'normal',
    helper: 'Birliğin güncel kurallarına göre hattında değişiklik gerekip gerekmediğini kontrol edebilirsin.',
  },
  {
    id: 'default-personal-unfinished',
    templateKey: 'personal-unfinished',
    introducedInVersion: 1,
    title: 'Evde yarım kalan önemli işlerini tamamla',
    category: 'personal',
    sortOrder: 100,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-personal-payments',
    templateKey: 'personal-payments',
    introducedInVersion: 1,
    title: 'Düzenli ödemelerini / aboneliklerini kontrol et',
    category: 'personal',
    sortOrder: 200,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-personal-contacts',
    templateKey: 'personal-contacts',
    introducedInVersion: 1,
    title: 'Yakınlarınla gerekli iletişim bilgilerini paylaş',
    category: 'personal',
    sortOrder: 300,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-personal-tasks',
    templateKey: 'personal-tasks',
    introducedInVersion: 1,
    title: 'Gitmeden önceki kişisel işlerini tamamla',
    category: 'personal',
    sortOrder: 400,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-underwear',
    templateKey: 'bag-underwear',
    introducedInVersion: 1,
    title: 'Önerilen: Yeterli iç çamaşırı hazırla',
    category: 'bagEquipment',
    sortOrder: 100,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-socks',
    templateKey: 'bag-socks',
    introducedInVersion: 1,
    title: 'Önerilen: Yeterli çorap hazırla',
    category: 'bagEquipment',
    sortOrder: 200,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-personal-care',
    templateKey: 'bag-personal-care',
    introducedInVersion: 1,
    title: 'Önerilen: Kişisel bakım ürünlerini hazırla',
    category: 'bagEquipment',
    sortOrder: 300,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-dental',
    templateKey: 'bag-dental',
    introducedInVersion: 1,
    title: 'Önerilen: Diş bakım ürünlerini hazırla',
    category: 'bagEquipment',
    sortOrder: 400,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-slippers',
    templateKey: 'bag-slippers',
    introducedInVersion: 1,
    title: 'Önerilen: Terlik hazırla',
    category: 'bagEquipment',
    sortOrder: 500,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-towel',
    templateKey: 'bag-towel',
    introducedInVersion: 1,
    title: 'Önerilen: Havlu hazırla',
    category: 'bagEquipment',
    sortOrder: 600,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-laundry-bag',
    templateKey: 'bag-laundry-bag',
    introducedInVersion: 1,
    title: 'Önerilen: Çamaşır filesi hazırla',
    category: 'bagEquipment',
    sortOrder: 700,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-lock',
    templateKey: 'bag-lock',
    introducedInVersion: 1,
    title: 'Önerilen: Dolap / bot kilidi hazırla',
    category: 'bagEquipment',
    sortOrder: 800,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-insoles',
    templateKey: 'bag-insoles',
    introducedInVersion: 1,
    title: 'Önerilen: Uygun tabanlık hazırla',
    category: 'bagEquipment',
    sortOrder: 900,
    priority: 'normal',
    helper: null,
  },
  {
    id: 'default-bag-small-needs',
    templateKey: 'bag-small-needs',
    introducedInVersion: 1,
    title: 'Önerilen: Küçük kişisel ihtiyaçlarını hazırla',
    category: 'bagEquipment',
    sortOrder: 1000,
    priority: 'normal',
    helper: null,
  },
] as const;
